### ISSUE TITLE
Support for USB C

### ISSUE THREAD

**Issue by hawktang** [newAM/monitorcontrol#170]
USB C listed as 27

monitorcontrol --set-input-source 27 

is not working

Monitor 1: U3219Q
Available Inputs:
        InputSource.DP1*
        InputSource.HDMI1
        27
Monitor 2:
Available Inputs:
Monitor 3: VG27AQ
Available Inputs:
        InputSource.DP1*
        InputSource.HDMI1
        InputSource.HDMI2

**Comment by newAM** [comment]
USB type C is not part of the specification, if this doesn't work there's not much that can be done about it.

**Comment by kojiishi** [comment]
`monitor.get_input_source()` fails if the current is an unlisted value, such as 27. I'm using DELL monitors on Windows.

```
Traceback (most recent call last):
  File "C:\Users\kojii\AppData\Local\Programs\Python\Python310\lib\site-packages\monitorcontrol\monitorcontrol.py", line 464, in get_input_source
    return InputSource(value)
  File "C:\Users\kojii\AppData\Local\Programs\Python\Python310\lib\enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "C:\Users\kojii\AppData\Local\Programs\Python\Python310\lib\enum.py", line 710, in __new__
    raise ve_exc
ValueError: 27 is not a valid InputSource

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\src\bin\dpswitch.py", line 35, in <module>
    run()
  File "C:\src\bin\dpswitch.py", line 25, in run
    current_input = monitor.get_input_source()
  File "C:\Users\kojii\AppData\Local\Programs\Python\Python310\lib\site-packages\monitorcontrol\monitorcontrol.py", line 466, in get_input_source
    raise InputSourceValueError(f"{value} is not a valid InputSource", value)
monitorcontrol.monitorcontrol.InputSourceValueError: 27 is not a valid InputSource
```

I'm not sure if the specification allows such non-standard values, but great if it can return the raw value without errors.

**Comment by aminomancer** [comment]
Does the spec really matter? Some other software I'm using returns an identifier `2`. Is there a fundamental reason we couldn't send it to the monitor? The monitor's DDC implementation might be nonstandard and then maybe it works. If so, you could put it behind an optional flag, or make the error a warning.

**Comment by newAM** [comment]
> Does the spec really matter? Some other software I'm using returns an identifier `2`. Is there a fundamental reason we couldn't send it to the monitor? The monitor's DDC implementation might be nonstandard and then maybe it works. If so, you could put it behind an optional flag, or make the error a warning.

The problem is there isn't even a defacto standard.  Different manufacturers use different values for USB-C monitors.

I'm happy to remove the `InputSourceValueError` and replace it with a warning though.

**Comment by aminomancer** [comment]
> Removed the `InputSourceValueError` in [#389](https://github.com/newAM/monitorcontrol/pull/389), should be easy enough to write code for Type-C monitors now.

Does this affect `set_input_source`? What I was hoping was that I could use a hotkey to tell my monitor to switch to my USB-C input source. But `--set-input-source` still returns an error and a list of available source strings. I assume if my monitor returns a nonstandard source value when queried, then there's a good chance passing that value would correctly set the input source. Is there a risk in trying to pass integer values to the monitor?

**Comment by newAM** [comment]
Ah, I missed that the CLI still had input validation against the enum, I've opened #397 to fix that.

**Comment by newAM** [comment]
Fixed in [4.1.0](https://github.com/newAM/monitorcontrol/releases/tag/4.1.0)

**Comment by aminomancer** [comment]
It still throws in set_input_source:

```
$ monitorcontrol --set-input-source 2
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Program Files\Python313\Scripts\monitorcontrol.exe\__main__.py", line 7, in <module>
    sys.exit(main())
             ~~~~^^
  File "C:\Program Files\Python313\Lib\site-packages\monitorcontrol\__main__.py", line 148, in main
    monitor_obj.set_input_source(args.set_input_source)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python313\Lib\site-packages\monitorcontrol\monitorcontrol.py", line 448, in set_input_source
    mode_value = getattr(InputSource, value.upper()).value
                 ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'InputSource' has no attribute '2'
```

**Comment by aminomancer** [comment]
No problem! Thanks for working on it.

**Comment by newAM** [comment]
Fixed in [4.1.1](https://github.com/newAM/monitorcontrol/releases/tag/4.1.1)
