### ISSUE TITLE
ValueError: 27 is not a valid InputSource

### ISSUE THREAD

**Issue by madsensh** [newAM/monitorcontrol#258]
Getting an error regarding an unrecognized InputSource value.  Based on my monitor's inputs and reviewing the list on lines 28-46 of monitorcontrol.py, I'm guessing it may be for the USB-C input.  I can try creating a fork and adding that as a possible value, but wanted to double check with you if there is some standard list of input codes I should be referencing.

---

* Monitor manufacturer and model number: Dell U4924DW
* Input source (HDMI, VGA, display port, ect.): USB-C
* Output device (video card, discrete graphics, ect.):
* Operating system: Windows 10
* Python version: 3.11.1
* monitorcontrol version (`monitorcontrol --version`): 3.0.3

# Steps to Reproduce
monitorcontrol --get-monitors -vvvv

Traceback (most recent call last):
  File "C:\Users\user\apps\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\monitorcontrol\monitorcontrol.py", line 397, in get_input_source
    return InputSource(value)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\apps\WPy64-31110\python-3.11.1.amd64\Lib\enum.py", line 715, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\apps\WPy64-31110\python-3.11.1.amd64\Lib\enum.py", line 1131, in __new__
    raise ve_exc
ValueError: 27 is not a valid InputSource

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\user\apps\WPy64-31110\python-3.11.1.amd64\Scripts\monitorcontrol.exe\__main__.py", line 7, in <module>
  File "C:\Users\user\apps\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\monitorcontrol\__main__.py", line 158, in main
    current_input = monitor_obj.get_input_source()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\apps\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\monitorcontrol\monitorcontrol.py", line 399, in get_input_source
    raise InputSourceValueError(
monitorcontrol.monitorcontrol.InputSourceValueError: 27 is not a valid InputSource

**Comment by newAM** [comment]
Sadly Type-C is not part of the VESA standard, and there doesn't seem to be a consistent pseudo-standard.  I sent an email to VESA asking if they plan to update the specification for Type-C but have not heard back.

There's more discussion in #242

**Comment by madsensh** [comment]
Thanks for the quick reply.  As it turns out, for my simple use case, which is to change back to the displayport input (can't use Dell Display Manager due to work-issued laptop), all I needed was this.    Seems to run ok as long as monitorcontrol doesn't try to enumerate the inputs. 

monitorcontrol --set-input-source DP1
