### ISSUE TITLE
monitorcontrol.vcp' has no attribute 'get_vcps

### ISSUE THREAD

**Issue by thewh1teagle** [newAM/monitorcontrol#364]
* Monitor manufacturer and model number: Xiaomi Curved 30" RMMNT30HFCW 
* Input source (HDMI, VGA, display port, ect.): HDMI
* Output device (video card, discrete graphics, ect.): HDMI1 macos mini m1
* Operating system: macos
* Python version: 3.9.6
* monitorcontrol version (`monitorcontrol --version`): 3.1.0

# Steps to Reproduce

```console
./monitorcontrol/venv/bin/monitorcontrol --get-monitors
Traceback (most recent call last):
  File "/Volumes/Internal/cec-rs/examples/cec-example-cli/./monitorcontrol/venv/bin/monitorcontrol", line 8, in <module>
    sys.exit(main())
  File "/Volumes/Internal/cec-rs/examples/cec-example-cli/monitorcontrol/venv/lib/python3.9/site-packages/monitorcontrol/__main__.py", line 155, in main
    for monitor_index, monitor_obj in enumerate(get_monitors(), 0):
  File "/Volumes/Internal/cec-rs/examples/cec-example-cli/monitorcontrol/venv/lib/python3.9/site-packages/monitorcontrol/monitorcontrol.py", line 546, in get_monitors
    return [Monitor(v) for v in vcp.get_vcps()]
AttributeError: module 'monitorcontrol.vcp' has no attribute 'get_vcps'

```

**Comment by newAM** [comment]
A backend for MacOS doesn't exist yet.  Happy to accept pull-requests!
